name = "KohnShamResolution"
uuid = "2d6a71d3-f4fe-4c59-9782-ebc44d5ef3e9"
authors = ["Théo Duez <42682941+Theozeud@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
